import marimo

__generated_with = "0.23.6"
app = marimo.App(width="medium")


@app.cell
def _():
    from pathlib import Path

    import marimo as mo

    from kernelforge.benchmark import (
        cleanup_generated_code,
        evaluate_entry,
        load_t_simple_entries,
        make_prompt,
    )

    TRITONBENCH_ROOT = Path("vendor/TritonBench")
    T_simple, errors, T_json, T_simple_alpaca = load_t_simple_entries(TRITONBENCH_ROOT)

    print(f"simp_alpac: {T_simple_alpaca[0].keys()}")
    print(f"jsonl: {T_json[0].keys()}")
    return (
        T_simple,
        T_simple_alpaca,
        cleanup_generated_code,
        errors,
        evaluate_entry,
        make_prompt,
        mo,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    The `simp_alpac` dataset contains a subset of the T dataset, with subjectively lower difficulty compared to the other problems. However, the Alpaca format does not contain enough metadata to fully associate each entry with its reference Torch code and the test code. Due to this, we must cross-reference with the full `TritonBench_T_v1.jsonl` dataset, so we can obtain the full entries and their related data but still being able to keep the simpler subset for initial testing.
    """)
    return


@app.cell
def _(T_simple_alpaca):
    print(T_simple_alpaca[0]["instruction"])
    return


@app.cell
def _(T_simple, T_simple_alpaca, errors):
    print(
        f"{len(errors)} error(s); T_simple = {len(T_simple)}; T_simp_alpac = {len(T_simple_alpaca)}"
    )
    T_simple[1]
    return


@app.cell
def _(T_simple, make_prompt, mo):
    mo.md(make_prompt(T_simple[1]))
    return


@app.cell
def _():
    from openai import OpenAI
    from os import environ

    LLM_API_KEY = environ.get("LIGHTNING_API_KEY")
    assert LLM_API_KEY is not None

    oai_client = OpenAI(base_url="https://lightning.ai/api/v1", api_key=LLM_API_KEY)
    return (oai_client,)


@app.cell
def _(make_prompt, mo, oai_client):
    # marimo's built-in cache is used to cache LLM responses, to avoid unnecessary costs
    @mo.persistent_cache
    def call_llm(
        entry, max_tokens: int = 2500, model: str = "lightning-ai/gemma-4-31B-it"
    ):
        # Prompt was generated by Claude Sonnet 4.6, was given information on TritonBench and how to properly
        # organize the messages between the system prompt and the user message. Conversation available at:
        # https://claude.ai/share/be71fef9-5c35-4080-acee-6119a9a66d82
        SYSTEM_PROMPT = """
    You are an expert GPU kernel engineer specializing in Triton, the open-source DSL \
    and compiler for writing high-performance, platform-agnostic GPU kernels.

    Your task: given a PyTorch reference implementation and a functional specification, \
    write an equivalent, self-contained Triton implementation.

    ## Triton Constraints
    - All kernel functions must use the `@triton.jit` decorator.
    - Access global memory exclusively through `tl.load` / `tl.store` with pointer \
    arithmetic. Never use Python-level indexing inside a `@triton.jit` kernel.
    - Tile computations using `tl.program_id` and `tl.arange`; expose block sizes as \
    `tl.constexpr` parameters.
    - Prefer native Triton ops (`tl.dot`, `tl.sum`, `tl.sqrt`, `tl.exp`, `tl.maximum`, \
    `tl.sigmoid`, etc.) over manual emulation.
    - Batch dimensions (e.g., B in BMM) must be handled via strides or grid flattening — \
    not by looping in Python.
    - Dtypes, broadcast semantics, and numerical defaults must match the reference exactly.

    ## Output Requirements
    - Output **only valid Python source code**. No Markdown fences, no prose, \
    no tests, no benchmarking code.
    - Begin your response with the import block: `import triton`, \
    `import triton.language as tl`, and any other required imports.
    - Define the public wrapper with **exactly** the name, parameters, defaults, \
    keyword-only arguments, and return structure given in the specification.
    - Include every `@triton.jit` kernel and helper function the wrapper depends on.
    - No core computation may silently fall back to PyTorch.
    """

        completion = oai_client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": make_prompt(entry)},
            ],
        )

        return completion

    return (call_llm,)


@app.cell
def _(T_simple, call_llm):
    result = call_llm(T_simple[25])
    return (result,)


@app.cell
def _(cleanup_generated_code, mo, result):
    mo.md(f"""
    ```python
    {cleanup_generated_code(result.choices[0].message.content)}
    ```
    """)
    return


@app.cell
def _(call_llm, evaluate_entry):
    def evaluate_llm_entry(entry, timeout: int = 180):
        pred_code = call_llm(entry).choices[0].message.content
        return evaluate_entry(
            entry,
            pred_code=pred_code,
            timeout=timeout,
        )

    return (evaluate_llm_entry,)


@app.cell
def _(T_simple, mo):
    _cases = {c["file"][:-3]: c for c in T_simple}
    chosen_case = mo.ui.dropdown(_cases).form()
    mo.md(f"""
    {chosen_case}
    """)
    return (chosen_case,)


@app.cell
def _(chosen_case):
    chosen_case.value
    return


@app.cell
def _(chosen_case, evaluate_llm_entry):
    chosen_eval_result = evaluate_llm_entry(chosen_case.value)
    chosen_eval_result
    return (chosen_eval_result,)


@app.cell
def _(chosen_eval_result):
    if not chosen_eval_result["pred"]["ok"]:
        print(chosen_eval_result["pred"]["stderr"])
    return


@app.cell
def _(chosen_eval_result):
    chosen_eval_result["pred"]
    return


if __name__ == "__main__":
    app.run()
